[package]
name = "influx_db_client_derive"
version = "0.1.0"
authors = ["max"]
edition = "2018"

[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
proc-macro2 = "^1"
quote = "^1"
syn = "^1"
serde_json = "^1.0.2"
